### ISSUE TITLE
一个很严重的bug，关于微信分享

### ISSUE THREAD

**Issue by 3Spiders** [hrwhisper/baiduShare#9]
http://dev.miguai.top:19552/#/find/detail/11783，如果我的链接是这个，微信生成二维码的时候会自动把#及#号后面内容干掉，让我很苦恼，这应该是微信生成二维码时候的bug，希望能解决，我用草料直接生成二维码不会出现这个问题

**Comment by xtlsoft** [comment]
hhh
这是微信问题，发issue有用吗?
This is the problem of Wechat, send an issue is useless.

http://dev.miguai.top:19552/#/find/detail/11783，如果我的链接是这个，微信生成二维码的时候会自动把#及#号后面内容干掉，让我很苦恼，这应该是微信生成二维码时候的bug，希望能解决，我用草料直接生成二维码不会出现这个问题 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by 3Spiders** [comment]
这不是微信的问题，因为我用其他生成器生成的时候，是不会截断#号及后面内容，应该是百度分享生成二维码的时候，添加了#weixin...的标记，并且把之前url#内容干掉，这对单页面应用不友好

**Comment by 3Spiders** [comment]
已解决，是我自己的问题，分享设置统计回流，会自动添加#号，把回流关掉就可以了
